@startuml
title SIP INVITE Sending Flow

skinparam monochrome true
autonumber "F00 "
hide footbox
skinparam BoxPadding 40

skinparam headerFontSize 14
'skinparam headerFontColor red
header SIP-0

box "caller"
participant "Invite Transaction Client" as UAC_ITC << UAC >>
end box

box "proxy"
participant "Invite Transaction Server" as Proxy_ITS << Server >>
participant "Invite Transaction Client" as Proxy_ITC << Server >>
end box

box "callee"
participant "Invite Transaction Server" as UAS_ITS << UAS >>
end box

'hnote over UAC_ITC: None
UAC_ITC -> Proxy_ITS: INVITE
activate UAC_ITC
hnote over UAC_ITC: Calling
activate Proxy_ITS
hnote over Proxy_ITS: Proceeding
UAC_ITC <- Proxy_ITS: 100 Trying
hnote over UAC_ITC: Proceeding
'hnote over Proxy_ITC: None
Proxy_ITS -> Proxy_ITC: INVITE
activate Proxy_ITC
Proxy_ITC -> UAS_ITS: INVITE
hnote over Proxy_ITC: Calling
activate UAS_ITS
hnote over UAS_ITS: Proceeding
Proxy_ITC <- UAS_ITS: 180 Ringing
note right of UAS_ITS: Ringing
hnote over Proxy_ITC: Proceeding
Proxy_ITS <- Proxy_ITC: 180 Ringing
UAC_ITC <- Proxy_ITS: 180 Ringing
note left of UAC_ITC: Ringing
== wait for HUMAN input ==

skinparam footerFontSize 14
'skinparam footerFontColor red
footer INVITE request is delivered hop-by-hop

@enduml